package escritorios;

import formularios.FormularioEditarCliente;
import formularios.FormularioRegistrarCliente;
import java.awt.Frame;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import operacionesCliente.ABM_Cliente;
import operacionesCliente.InterfacesGraficasCliente;
import operacionesCliente.TablaCliente;
import operacionesCuenta.InterfacesGraficasCuenta;
import operacionesDireccion.InterfacesGraficasDireccion;
import clasesUtilidadGeneral.OperacionesUtiles;
import operacionesTelefono.InterfacesGraficasTelefono;
import operacionesVenta.OperacionesSecundariasVenta;
import operacionesVenta.TablaVenta;
import principal.Main;
import principal.MaterialButton;

/**
 *
 * @author TELCOM MPC
 */
public class PrincipalCliente extends javax.swing.JInternalFrame {

    //OperacionesCliente opC = new OperacionesCliente();
//    OperacionesCuenta opCta = new OperacionesCuenta();
    OperacionesSecundariasVenta ot = new OperacionesSecundariasVenta();
    //OperacionesRegistrarVenta oRV = new OperacionesRegistrarVenta();
    InterfacesGraficasCliente i = new InterfacesGraficasCliente();
    Frame j = new Frame();
    TablaCliente t = new TablaCliente();
    InterfacesGraficasCuenta ic = new InterfacesGraficasCuenta();
    TablaVenta tv = new TablaVenta();
    InterfacesGraficasDireccion id = new InterfacesGraficasDireccion();
    ABM_Cliente abm = new ABM_Cliente();
    InterfacesGraficasTelefono it = new InterfacesGraficasTelefono();

    /**
     * Creates new form PrincipalCliente
     */
    public PrincipalCliente() {
        initComponents();
        btnSeleccionarCliente.setVisible(false);
    }

    public JTable getTabla() {
        return tabla;
    }

    public void setTabla(JTable tabla) {
        this.tabla = tabla;
    }

    public MaterialButton getBtnSeleccionarCliente() {
        return btnSeleccionarCliente;
    }

    public void setBtnSeleccionarCliente(MaterialButton btnSeleccionarCliente) {
        this.btnSeleccionarCliente = btnSeleccionarCliente;
    }

    public TablaCliente ObjetoTablaConDatos() {
        t.setTabla(tabla);
        t.setConsultaList("from Cliente");
        t.obtenerListaConsulta();
        t.obtenerIdTablaCliente();
        return t;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_1_primario = new javax.swing.JPanel();
        btnSeleccionarCliente = new principal.MaterialButton();
        txtBuscar = new javax.swing.JTextField();
        btnnuevocliente = new principal.MaterialButton();
        btnCuenta = new principal.MaterialButton();
        btnnEditarCl = new principal.MaterialButton();
        btnEliminarCli = new principal.MaterialButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblSalir = new javax.swing.JLabel();
        btnTelefonos = new principal.MaterialButton();
        btnDirecciones = new principal.MaterialButton();

        panel_1_primario.setBackground(new java.awt.Color(204, 0, 0));

        btnSeleccionarCliente.setBackground(new java.awt.Color(0, 0, 0,60));
        btnSeleccionarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnSeleccionarCliente.setText("SELECCIONAR CLIENTE");
        btnSeleccionarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSeleccionarCliente.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        btnSeleccionarCliente.setMaximumSize(new java.awt.Dimension(130, 35));
        btnSeleccionarCliente.setMinimumSize(new java.awt.Dimension(130, 35));
        btnSeleccionarCliente.setPreferredSize(new java.awt.Dimension(130, 35));
        btnSeleccionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarClienteActionPerformed(evt);
            }
        });

        txtBuscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.gray, java.awt.Color.lightGray));
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarKeyTyped(evt);
            }
        });

        btnnuevocliente.setBackground(new java.awt.Color(0, 0, 0,60));
        btnnuevocliente.setForeground(new java.awt.Color(255, 255, 255));
        btnnuevocliente.setText("NUEVO CLIENTE");
        btnnuevocliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnnuevocliente.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        btnnuevocliente.setMaximumSize(new java.awt.Dimension(130, 35));
        btnnuevocliente.setMinimumSize(new java.awt.Dimension(130, 35));
        btnnuevocliente.setPreferredSize(new java.awt.Dimension(130, 35));
        btnnuevocliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoclienteActionPerformed(evt);
            }
        });

        btnCuenta.setBackground(new java.awt.Color(0, 0, 0,60));
        btnCuenta.setForeground(new java.awt.Color(255, 255, 255));
        btnCuenta.setText("CUENTA");
        btnCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCuenta.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        btnCuenta.setMaximumSize(new java.awt.Dimension(130, 35));
        btnCuenta.setMinimumSize(new java.awt.Dimension(130, 35));
        btnCuenta.setPreferredSize(new java.awt.Dimension(130, 35));
        btnCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuentaActionPerformed(evt);
            }
        });

        btnnEditarCl.setBackground(new java.awt.Color(0, 0, 0,60));
        btnnEditarCl.setForeground(new java.awt.Color(255, 255, 255));
        btnnEditarCl.setText("EDITAR CLIENTE");
        btnnEditarCl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnnEditarCl.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        btnnEditarCl.setMaximumSize(new java.awt.Dimension(130, 35));
        btnnEditarCl.setPreferredSize(new java.awt.Dimension(130, 35));
        btnnEditarCl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnEditarClActionPerformed(evt);
            }
        });

        btnEliminarCli.setBackground(new java.awt.Color(0, 0, 0,60));
        btnEliminarCli.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarCli.setText("ELIMINAR CLIENTE");
        btnEliminarCli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarCli.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        btnEliminarCli.setMaximumSize(new java.awt.Dimension(130, 35));
        btnEliminarCli.setMinimumSize(new java.awt.Dimension(130, 35));
        btnEliminarCli.setPreferredSize(new java.awt.Dimension(130, 35));
        btnEliminarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCliActionPerformed(evt);
            }
        });

        tabla.setBackground(new java.awt.Color(255, 255, 255));
        tabla.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        tabla.setForeground(new java.awt.Color(102, 0, 0));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOMBRE", "APELLIDO", "RAZON SOCIAL", "DIRECCION", "NUMERO/DIR", "LOCALIDAD", "PROVINCIA", "TELEFONO", "TIPO TEPLEFONO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabla.setDoubleBuffered(true);
        tabla.setRowHeight(40);
        tabla.setSelectionBackground(new java.awt.Color(102, 0, 0));
        tabla.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabla.getTableHeader().setReorderingAllowed(false);
        tabla.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                tablaComponentHidden(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);
        if (tabla.getColumnModel().getColumnCount() > 0) {
            tabla.getColumnModel().getColumn(0).setResizable(false);
            tabla.getColumnModel().getColumn(1).setResizable(false);
            tabla.getColumnModel().getColumn(2).setResizable(false);
            tabla.getColumnModel().getColumn(3).setResizable(false);
            tabla.getColumnModel().getColumn(4).setResizable(false);
            tabla.getColumnModel().getColumn(5).setResizable(false);
            tabla.getColumnModel().getColumn(6).setResizable(false);
            tabla.getColumnModel().getColumn(7).setResizable(false);
            tabla.getColumnModel().getColumn(8).setResizable(false);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CLIENTES");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user_group_man_man_80px.png"))); // NOI18N

        lblSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancel_60px.png"))); // NOI18N
        lblSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSalirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)))
        );

        btnTelefonos.setBackground(new java.awt.Color(0, 0, 0,60));
        btnTelefonos.setForeground(new java.awt.Color(255, 255, 255));
        btnTelefonos.setText("TELEFONOS");
        btnTelefonos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTelefonos.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        btnTelefonos.setMaximumSize(new java.awt.Dimension(130, 35));
        btnTelefonos.setMinimumSize(new java.awt.Dimension(130, 35));
        btnTelefonos.setPreferredSize(new java.awt.Dimension(130, 35));
        btnTelefonos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelefonosActionPerformed(evt);
            }
        });

        btnDirecciones.setBackground(new java.awt.Color(0, 0, 0,60));
        btnDirecciones.setForeground(new java.awt.Color(255, 255, 255));
        btnDirecciones.setText("DIRECCIONES");
        btnDirecciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDirecciones.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        btnDirecciones.setMaximumSize(new java.awt.Dimension(130, 35));
        btnDirecciones.setMinimumSize(new java.awt.Dimension(130, 35));
        btnDirecciones.setPreferredSize(new java.awt.Dimension(130, 35));
        btnDirecciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDireccionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_1_primarioLayout = new javax.swing.GroupLayout(panel_1_primario);
        panel_1_primario.setLayout(panel_1_primarioLayout);
        panel_1_primarioLayout.setHorizontalGroup(
            panel_1_primarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_1_primarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnnuevocliente, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnnEditarCl, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarCli, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDirecciones, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTelefonos, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSeleccionarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_1_primarioLayout.setVerticalGroup(
            panel_1_primarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_1_primarioLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_1_primarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeleccionarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarCli, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnnEditarCl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnnuevocliente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTelefonos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDirecciones, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 0, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_1_primario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_1_primario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarClienteActionPerformed
        if (ic.verificarFilaSeleccionadaCliente()) {
            switch (Main.getPrincipalAdmin().getVentas().getTipoFormulario()) {
                case 1:
                    tv.RellenarTablaClienteRegistrar(Main.getPrincipalAdmin().getRegistrarVentas());
                    break;
                case 2:
                    tv.RellenarTablaClienteEditar(Main.getPrincipalAdmin().getEditarVentas());
                    break;
            }
            this.dispose();
        }
    }//GEN-LAST:event_btnSeleccionarClienteActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        t.ejecutarRellenarTabla(this);
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void txtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarKeyTyped

    private void tablaComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tablaComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaComponentHidden

    private void btnnuevoclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoclienteActionPerformed
        // TODO add your handling code here:
        FormularioRegistrarCliente f = new FormularioRegistrarCliente(j, true);
        i.nuevoFormRegistrarCliente(f);
    }//GEN-LAST:event_btnnuevoclienteActionPerformed

    private void btnCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuentaActionPerformed
        // TODO add your handling code here:
        if (ic.verificarFilaSeleccionadaCliente()) {
            if (ic.verficarClienteNoconsumidorFinal(2)) {
                ic.ejecutarnuevaVentanaCuenta(Main.getPrincipalAdmin());
            }
        }

    }//GEN-LAST:event_btnCuentaActionPerformed

    private void btnEliminarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCliActionPerformed
        // TODO add your handling code here:

        if (ic.verificarFilaSeleccionadaCliente()) {
            if (ic.verficarClienteNoconsumidorFinal(1)) {
                if (OperacionesUtiles.mensajeEliminarRegistro()) {
                    if (abm.ejecutarEliminarCliente()) {
                        t.setEstadoConsulta(0);
                        t.ejecutarRellenarTabla(Main.getPrincipalAdmin().getCliente());
                        Main.getPrincipalAdmin().getCliente().setT(t);
                    }
                }
            }
        }

    }//GEN-LAST:event_btnEliminarCliActionPerformed

    private void btnnEditarClActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnEditarClActionPerformed
        // TODO add your handling code here:

        if (ic.verificarFilaSeleccionadaCliente()) {
            if (ic.verficarClienteNoconsumidorFinal(1)) {
                FormularioEditarCliente fe = new FormularioEditarCliente(j, true);
                i.nuevoFormEditarCliente(fe);
            }
        }
    }//GEN-LAST:event_btnnEditarClActionPerformed

    private void btnTelefonosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelefonosActionPerformed
        if (ic.verificarFilaSeleccionadaCliente()) {
            if (ic.verficarClienteNoconsumidorFinal(1)) {

                it.ejecutarnuevaVentanaTelefono(Main.getPrincipalAdmin(), "cliente");
            }
        }
    }//GEN-LAST:event_btnTelefonosActionPerformed

    private void btnDireccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDireccionesActionPerformed

        if (ic.verificarFilaSeleccionadaCliente()) {
            if (ic.verficarClienteNoconsumidorFinal(1)) {
                id.ejecutarnuevaVentanaDireccion(Main.getPrincipalAdmin(), "cliente");
            }
        }
    }//GEN-LAST:event_btnDireccionesActionPerformed

    private void lblSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseClicked
        this.dispose();
    }//GEN-LAST:event_lblSalirMouseClicked

    public JPanel getPanel_1_primario() {
        return panel_1_primario;
    }

    public void setPanel_1_primario(JPanel panel_1_primario) {
        this.panel_1_primario = panel_1_primario;
    }

    public MaterialButton getBtnDirecciones() {
        return btnDirecciones;
    }

    public void setBtnDirecciones(MaterialButton btnDirecciones) {
        this.btnDirecciones = btnDirecciones;
    }

    public MaterialButton getBtnTelefonos() {
        return btnTelefonos;
    }

    public void setBtnTelefonos(MaterialButton btnTelefonos) {
        this.btnTelefonos = btnTelefonos;
    }

    public MaterialButton getBtnnuevocliente() {
        return btnnuevocliente;
    }

    public void setBtnnuevocliente(MaterialButton btnnuevocliente) {
        this.btnnuevocliente = btnnuevocliente;
    }

    public JTextField getTxtBuscar() {
        return txtBuscar;
    }

    public void setTxtBuscar(JTextField txtBuscar) {
        this.txtBuscar = txtBuscar;
    }

    public MaterialButton getBtnEliminarCli() {
        return btnEliminarCli;
    }

    public void setBtnEliminarCli(MaterialButton btnEliminarCli) {
        this.btnEliminarCli = btnEliminarCli;
    }

    public MaterialButton getBtnnEditarCl() {
        return btnnEditarCl;
    }

    public void setBtnnEditarCl(MaterialButton btnnEditarCl) {
        this.btnnEditarCl = btnnEditarCl;
    }

    public MaterialButton getBtnCuenta() {
        return btnCuenta;
    }

    public void setBtnCuenta(MaterialButton btnCuenta) {
        this.btnCuenta = btnCuenta;
    }

    //***********************
    public TablaCliente getT() {
        return t;
    }

    public void setT(TablaCliente t) {
        this.t = t;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private principal.MaterialButton btnCuenta;
    private principal.MaterialButton btnDirecciones;
    private principal.MaterialButton btnEliminarCli;
    private principal.MaterialButton btnSeleccionarCliente;
    private principal.MaterialButton btnTelefonos;
    private principal.MaterialButton btnnEditarCl;
    private principal.MaterialButton btnnuevocliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSalir;
    private javax.swing.JPanel panel_1_primario;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
